openapi: 3.0.0
info:
  title: SportWare API
  description: API for managing sports courts reservations, schedules, reports, and billing.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local development server
paths:
  /reservations:
    get:
      summary: Get all reservations
      responses:
        '200':
          description: A list of reservations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reservation'
    post:
      summary: Create a new reservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reservation'
      responses:
        '201':
          description: Reservation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'
  /reservations/{id}:
    get:
      summary: Get a reservation by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the reservation
          schema:
            type: string
      responses:
        '200':
          description: A single reservation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'
    put:
      summary: Update a reservation
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the reservation
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reservation'
      responses:
        '200':
          description: Reservation updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'
    delete:
      summary: Delete a reservation
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the reservation
          schema:
            type: string
      responses:
        '204':
          description: Reservation deleted
  /courts:
    get:
      summary: Get all courts
      responses:
        '200':
          description: A list of courts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Court'
  /schedules:
    get:
      summary: Get all schedules
      responses:
        '200':
          description: A list of schedules
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Schedule'
components:
  schemas:
    Reservation:
      type: object
      properties:
        id:
          type: string
        courtId:
          type: string
        userId:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
    Court:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
    Schedule:
      type: object
      properties:
        id:
          type: string
        courtId:
          type: string
        date:
          type: string
          format: date
        availableSlots:
          type: array
          items:
            type: string
            format: date-time